#!/bin/bash
#set -x
# Copyright (c) 2023 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

source /usr/bin/gather_mce_logs

if [ -z $GATHER_HUB_RAN ] || [ $GATHER_HUB_RAN != true ];
then
  HUB_NAMESPACE=$(oc get multiclusterhubs.operator.open-cluster-management.io --all-namespaces --no-headers=true| awk '{ print $1 }')
  echo "Hub namespace: $HUB_NAMESPACE"
  oc get pods -n "$HUB_NAMESPACE" > ${BASE_COLLECTION_PATH}/gather-acm.log
  oc get csv -n "$HUB_NAMESPACE" >> ${BASE_COLLECTION_PATH}/gather-acm.log
  oc version >> ${BASE_COLLECTION_PATH}/gather-acm.log
  oc adm inspect  ns/"$HUB_NAMESPACE"  --dest-dir=must-gather
  oc adm inspect serviceaccounts --namespace "$HUB_NAMESPACE" --dest-dir=must-gather
  oc adm inspect roles --namespace "$HUB_NAMESPACE" --dest-dir=must-gather
  oc adm inspect  ns/open-cluster-management-hub  --dest-dir=must-gather
  oc adm inspect  ns/open-cluster-management-backup  --dest-dir=must-gather
  # request from https://bugzilla.redhat.com/show_bug.cgi?id=1853485
  oc get proxy -o yaml > ${BASE_COLLECTION_PATH}/gather-proxy.log
  oc adm inspect multiclusterhubs.operator.open-cluster-management.io --all-namespaces  --dest-dir=must-gather
  oc adm inspect klusterletaddonconfigs.agent.open-cluster-management.io --all-namespaces  --dest-dir=must-gather
  oc adm inspect validatingwebhookconfigurations.admissionregistration.k8s.io --all-namespaces --dest-dir=must-gather
  oc adm inspect mutatingwebhookconfigurations.admissionregistration.k8s.io --all-namespaces --dest-dir=must-gather
  oc adm inspect managedclusteraddons.addon.open-cluster-management.io  --all-namespaces  --dest-dir=must-gather
  oc adm inspect addondeploymentconfigs.addon.open-cluster-management.io --all-namespaces  --dest-dir=must-gather
  oc adm inspect searches.search.open-cluster-management.io --all-namespaces --dest-dir=must-gather
  oc adm inspect ns/openshift-monitoring  --dest-dir=must-gather
  oc adm inspect ns/open-cluster-management-issuer  --dest-dir=must-gather
  oc adm inspect restores.cluster.open-cluster-management.io --all-namespaces  --dest-dir=must-gather
  oc adm inspect backupschedules.cluster.open-cluster-management.io --all-namespaces  --dest-dir=must-gather
  oc adm inspect backupstoragelocations.velero.io --all-namespaces  --dest-dir=must-gather
  oc adm inspect backups.velero.io --all-namespaces  --dest-dir=must-gather
  oc adm inspect restores.velero.io --all-namespaces  --dest-dir=must-gather
  oc adm inspect ansiblejobs.tower.ansible.com --all-namespaces  --dest-dir=must-gather

  # Submariner Addon CRs
  oc adm inspect submarinerconfigs.submarineraddon.open-cluster-management.io --all-namespaces --dest-dir=must-gather
  oc adm inspect brokers.submariner.io --all-namespaces --dest-dir=must-gather

  # Multicluster GlobalHub information
  oc adm inspect multiclusterglobalhubs.operator.open-cluster-management.io --all-namespaces --dest-dir=must-gather
  if [ $? = 0 ];
  then
    # kafka
    oc adm inspect kafkas.kafka.strimzi.io --all-namespaces --dest-dir=must-gather
    oc adm inspect kafkatopics.kafka.strimzi.io --all-namespaces --dest-dir=must-gather
    oc adm inspect kafkausers.kafka.strimzi.io --all-namespaces --dest-dir=must-gather
    KAFKANS=`oc get kafkas.kafka.strimzi.io --all-namespaces --no-headers=true -o custom-columns=NAMESPACE:.metadata.namespace | sort -u`
    for kns in $KAFKANS;
    do
        oc adm inspect ns/"$kns"  --dest-dir=must-gather
    done
    # postgresql
    oc adm inspect postgresclusters.postgres-operator.crunchydata.com --all-namespaces --dest-dir=must-gather
    POSTGRESNS=`oc get postgresclusters.postgres-operator.crunchydata.com --all-namespaces --no-headers=true -o custom-columns=NAMESPACE:.metadata.namespace | sort -u`
    for pns in $POSTGRESNS;
    do
        oc adm inspect ns/"$pns"  --dest-dir=must-gather
    done
    GLOBALHUB_NAMESPACE=$(oc get multiclusterglobalhubs.operator.open-cluster-management.io --all-namespaces --no-headers=true| awk '{ print $1 }')
    echo "GlobalHub namespace: $GLOBALHUB_NAMESPACE"
    oc adm inspect ns/"$GLOBALHUB_NAMESPACE" --dest-dir=must-gather
  fi

  # Multicluster Global Hub Agent information
  oc adm inspect ns/multicluster-global-hub-agent --dest-dir=must-gather

  # Get disconneted information
  oc adm inspect imagecontentsourcepolicies.operator.openshift.io  --all-namespaces --dest-dir=must-gather

  # version information
  oc adm --dest-dir=must-gather inspect clusterversions
  oc adm --dest-dir=must-gather inspect csv -n "$HUB_NAMESPACE"

  # OpenShift console plug-in enablement
  oc adm inspect consoles.operator.openshift.io --dest-dir=must-gather

  export GATHER_HUB_RAN=true
fi
