#! /bin/bash
# Copyright (c) 2023 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
# shellcheck source=collection-scripts/gather_utils
source "${SCRIPT_DIR}/gather_utils"

log "Starting Disaster Recovery (DR) must-gather"

if run_inspect drclusters.ramendr.openshift.io; then
  if [[ "${GATHER_CONTEXT}" == "true" ]]; then
    gather_mce_logs
    gather_hub_logs
  fi

  run_inspect mirrorpeers.multicluster.odf.openshift.io
  run_inspect drpolicies.ramendr.openshift.io
  run_inspect drplacementcontrols.ramendr.openshift.io --all-namespaces
else
  log "Skipping DR logs collection because there's no DRCluster resources configured."
fi
