#! /bin/bash
# Copyright (c) 2023 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
source ${SCRIPT_DIR}/gather_utils

log "Starting Application lifecycle must-gather"

if [[ "${GATHER_CONTEXT}" == "true" ]]; then
    ${SCRIPT_DIR}/gather_mce_logs
    ${SCRIPT_DIR}/gather_hub_logs
fi

# application resources
run_inspect applications.app.k8s.io --all-namespaces
run_inspect channels.apps.open-cluster-management.io --all-namespaces
run_inspect deployables.apps.open-cluster-management.io --all-namespaces
run_inspect helmreleases.apps.open-cluster-management.io --all-namespaces
run_inspect placementdecisions.cluster.open-cluster-management.io --all-namespaces
run_inspect placements.cluster.open-cluster-management.io --all-namespaces
run_inspect placementrules.apps.open-cluster-management.io --all-namespaces
run_inspect subscriptions.apps.open-cluster-management.io --all-namespaces
run_inspect subscriptionreports.apps.open-cluster-management.io --all-namespaces

# gitops resources
run_inspect gitopscluster.apps.open-cluster-management.io --all-namespaces
run_inspect argocd.argoproj.io --all-namespaces
run_inspect applicationsets.argoproj.io --all-namespaces
run_inspect managedclustersetbinding.cluster.open-cluster-management.io
run_inspect managedclusterset.cluster.open-cluster-management.io
ARGONS=$(oc get argocd --all-namespaces --no-headers=true -o custom-columns=NAMESPACE:.metadata.namespace | sort -u)
for a in $ARGONS; do
    run_inspect ns/"$a"
done
run_inspect multiclusterapplicationsetreports.apps.open-cluster-management.io --all-namespaces
run_inspect clusterpermission.rbac.open-cluster-management.io --all-namespaces
