#! /bin/bash
# Copyright (c) 2023 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
source ${SCRIPT_DIR}/gather_utils

log "Starting Governance Policy Framework (GRC) must-gather"

if [[ "${GATHER_CONTEXT}" == "true" ]]; then
    ${SCRIPT_DIR}/gather_mce_logs
    ${SCRIPT_DIR}/gather_hub_logs
fi

run_inspect policies.policy.open-cluster-management.io --all-namespaces
run_inspect policysets.policy.open-cluster-management.io --all-namespaces
run_inspect policyautomations.policy.open-cluster-management.io --all-namespaces
run_inspect placementbindings.policy.open-cluster-management.io --all-namespaces
