#!/bin/bash
#set -x
# Copyright (c) 2023 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

source gather_mce_logs
source gather_hub_logs

# application resources
oc adm inspect applications.app.k8s.io --all-namespaces  --dest-dir=must-gather
oc adm inspect channels.apps.open-cluster-management.io --all-namespaces  --dest-dir=must-gather
oc adm inspect deployables.apps.open-cluster-management.io --all-namespaces  --dest-dir=must-gather
oc adm inspect helmreleases.apps.open-cluster-management.io --all-namespaces  --dest-dir=must-gather
oc adm inspect placementdecisions.cluster.open-cluster-management.io --all-namespaces  --dest-dir=must-gather
oc adm inspect placements.cluster.open-cluster-management.io --all-namespaces  --dest-dir=must-gather
oc adm inspect placementrules.apps.open-cluster-management.io --all-namespaces  --dest-dir=must-gather
oc adm inspect subscriptions.apps.open-cluster-management.io --all-namespaces  --dest-dir=must-gather
oc adm inspect subscriptionreports.apps.open-cluster-management.io --all-namespaces --dest-dir=must-gather

# gitops resources
oc adm inspect gitopscluster.apps.open-cluster-management.io --all-namespaces --dest-dir=must-gather
oc adm inspect argocd.argoproj.io --all-namespaces --dest-dir=must-gather
oc adm inspect applicationsets.argoproj.io --all-namespaces --dest-dir=must-gather
oc adm inspect managedclustersetbinding.cluster.open-cluster-management.io  --dest-dir=must-gather
oc adm inspect managedclusterset.cluster.open-cluster-management.io  --dest-dir=must-gather
ARGONS=`oc get argocd --all-namespaces --no-headers=true -o custom-columns=NAMESPACE:.metadata.namespace | sort -u`
for a in $ARGONS;
do
    oc adm inspect ns/"$a"  --dest-dir=must-gather
done
oc adm inspect multiclusterapplicationsetreports.apps.open-cluster-management.io --all-namespaces --dest-dir=must-gather
oc adm inspect clusterpermission.rbac.open-cluster-management.io --all-namespaces --dest-dir=must-gather
