#! /bin/bash
# Copyright (c) 2023 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
# shellcheck source=collection-scripts/gather_utils
source "${SCRIPT_DIR}/gather_utils"

# Set a file path for the gather managed clusters.
MANAGED_CLUSTER_FILE_PATH=${BASE_COLLECTION_PATH}/gather-managed.log

HC_NAME=${HC_NAME:-""}
HC_NAMESPACE=${HC_NAMESPACE:-"clusters"}

check_managed_clusters() {
  touch "${MANAGED_CLUSTER_FILE_PATH}"
  log "The list of managed clusters that are configured on this hub:" 2>&1 | tee -a "${MANAGED_CLUSTER_FILE_PATH}"

  # These calls will change with new API
  oc get managedclusters.cluster.open-cluster-management.io --all-namespaces 2>&1 | tee -a "${MANAGED_CLUSTER_FILE_PATH}"

  # to capture details in the managed cluster namespace to debug hive issues
  # refer https://github.com/open-cluster-management/backlog/issues/2682
  local mc_namespaces
  mapfile -t mc_namespaces < <(oc get clusterdeployments.hive.openshift.io -A -o custom-columns=":metadata.namespace" --no-headers=true | sort -u)
  run_inspect_batched_by_name namespace "${mc_namespaces[@]}"
}

gather_service_and_event_logs_for_failed_agents() {
  local gather_dir=${1}
  local dir
  agent_cluster_install_list=$(oc get agentclusterinstalls.extensions.hive.openshift.io --all-namespaces -o json)
  total_installs=$(echo "${agent_cluster_install_list}" | jq '.items | length' 2>/dev/null)
  total_installs=${total_installs:-0}
  cluster_ingress=$(oc get ingress.config.openshift.io cluster -o jsonpath='{.spec.domain}')
  cluster_ingress=${cluster_ingress:-"<not-found>"}
  assisted_service_ingress="https://assisted-service-${DEPLOYMENT_NAMESPACE}.${cluster_ingress}/"

  if [[ "${total_installs}" -gt 0 ]]; then
    for idx in $(seq 0 $((total_installs - 1))); do
      install_json=$(echo "${agent_cluster_install_list}" | jq ".items[${idx}]")
      install_name=$(echo "${install_json}" | jq -r '.metadata.name')
      install_namespace=$(echo "${install_json}" | jq -r '.metadata.namespace')
      dir=${gather_dir}/namespaces/${install_namespace}/extensions.hive.openshift.io/agentclusterinstalls

      failed=$(echo "${install_json}" | jq -r '.status.conditions[] | select(.type == "Failed") | .status')
      if [[ "${failed}" == "False" ]]; then
        log "skipping logs and events for non-failed cluster ${install_name}"
        continue
      fi

      logsURL=$(echo "${install_json}" | jq -r '.status.debugInfo.logsURL')
      if [[ -n "${logsURL}" ]]; then
        if [[ "${logsURL}" != "${assisted_service_ingress}"* ]]; then
          log "WARN" "cluster ${install_name} logs URL does not align with the cluster ingress ${cluster_ingress}. Skipping logs collection. Fetch logs manually if required."
        else
          mkdir -p "${dir}"
          curl --connect-timeout 10 --max-time 30 -k -o "${dir}/${install_name}.logs.tar" "${logsURL}"
        fi
      fi

      eventsURL=$(echo "${install_json}" | jq -r '.status.debugInfo.eventsURL')
      if [[ -n "${eventsURL}" ]]; then
        if [[ "${eventsURL}" != "${assisted_service_ingress}"* ]]; then
          log "WARN" "cluster ${install_name} events URL does not align with the cluster ingress ${cluster_ingress}. Skipping events collection. Fetch events manually if required."
        else
          mkdir -p "${dir}"
          curl --connect-timeout 10 --max-time 30 -k -o "${dir}/${install_name}.events" "${eventsURL}"
        fi
      fi
    done
  else
    log "No agentclusterinstalls found"
  fi
}

gather_hub() {
  if [[ -z "${MCE_NAME}" ]]; then
    MCE_NAME=$(
      oc get multiclusterengines.multicluster.openshift.io --all-namespaces --no-headers=true | head -n 1 | awk '{ print $1 }'
    )

    if [[ -z "${MCE_NAME}" ]]; then
      log "WARN" "No MultiClusterEngine resource found. Skipping MCE hub gather."
      return 1
    fi
  fi

  if [[ -z "${OPERATOR_NAMESPACE}" ]] || [[ -z "${DEPLOYMENT_NAMESPACE}" ]]; then
    OPERATOR_NAMESPACE=$(
      oc get pod -l control-plane=backplane-operator --all-namespaces --no-headers=true | head -n 1 | awk '{ print $1 }'
    )
    DEPLOYMENT_NAMESPACE=$(oc get multiclusterengines.multicluster.openshift.io "${MCE_NAME}" -o jsonpath='{.spec.targetNamespace}')

    if [[ -z "${OPERATOR_NAMESPACE}" ]] || [[ -z "${DEPLOYMENT_NAMESPACE}" ]]; then
      log "WARN" "Could not resolve MCE operator nor deployment namespace. Skipping MCE hub gather."
      return 1
    fi
  fi

  {
    print_with_header "Openshift CLI version" "$(oc version)"
    print_with_header "ClusterServiceVersion in namespace ${OPERATOR_NAMESPACE}" \
      "$(oc get clusterserviceversions.operators.coreos.com -n "${OPERATOR_NAMESPACE}")"
    print_with_header "MultiClusterEngine resource in namespace ${OPERATOR_NAMESPACE}" \
      "$(oc get multiclusterengines.multicluster.openshift.io -n "${OPERATOR_NAMESPACE}")"
  } >"${BASE_COLLECTION_PATH}/gather-mce.log"

  check_managed_clusters

  # If the namespaces are different, capture the pods in each namespace.
  if [[ $DEPLOYMENT_NAMESPACE != "$OPERATOR_NAMESPACE" ]]; then
    log "MCE target and operator namespace are different"

    {
      print_with_header "Pods in namespace ${OPERATOR_NAMESPACE}" \
        "$(oc get pods -n "${OPERATOR_NAMESPACE}")"
      print_with_header "Pods in namespace ${DEPLOYMENT_NAMESPACE}" \
        "$(oc get pods -n "${DEPLOYMENT_NAMESPACE}")"
    } >>"${BASE_COLLECTION_PATH}/gather-mce.log"

    run_inspect ns/"${OPERATOR_NAMESPACE}"
    run_inspect ns/"${DEPLOYMENT_NAMESPACE}"
    run_inspect serviceaccounts --namespace "${DEPLOYMENT_NAMESPACE}"
    run_inspect roles --namespace "${DEPLOYMENT_NAMESPACE}"
  else
    print_with_header "Pods in namespace ${OPERATOR_NAMESPACE}" \
      "$(oc get pods -n "${OPERATOR_NAMESPACE}")" >>"${BASE_COLLECTION_PATH}/gather-mce.log"

    run_inspect ns/"${OPERATOR_NAMESPACE}"
    run_inspect serviceaccounts --namespace "${OPERATOR_NAMESPACE}"
    run_inspect roles --namespace "${OPERATOR_NAMESPACE}"
  fi

  deployment_json=$(oc get deployments -n "${DEPLOYMENT_NAMESPACE}" -o json)
  max_name_length=$(echo "${deployment_json}" | jq -r '[.items[].metadata.name | length] | max')
  {
    echo -e "DEPLOYMENT\tVERSION"
    echo "${deployment_json}" |
      jq -r '.items[].metadata | 
        .name + "\t" + (.annotations["installer.multicluster.openshift.io/release-version"] //
        .labels.chart // 
        "-")'
  } | awk '{ printf "%-'"${max_name_length}"'s %s\n", $1, $2 }' >>"${BASE_COLLECTION_PATH}/gather-mce.log"

  run_inspect ns/open-cluster-management-hub
  run_inspect proxies.config.openshift.io
  echo "proxy info now at cluster-scoped-resources/config.openshift.io/proxies" \
    >"${BASE_COLLECTION_PATH}/gather-proxy-mce.log"
  run_inspect customresourcedefinition.apiextensions.k8s.io
  run_inspect ns/hive
  run_inspect multiclusterengines.multicluster.openshift.io --all-namespaces
  run_inspect internalenginecomponents.multicluster.openshift.io --all-namespaces
  run_inspect hiveconfigs.hive.openshift.io --all-namespaces

  run_inspect clusterserviceversions.operators.coreos.com --all-namespaces
  run_inspect packagemanifests.packages.operators.coreos.com multicluster-engine -n openshift-marketplace
  run_inspect catalogsources.operators.coreos.com --all-namespaces
  run_inspect subscriptions.operators.coreos.com --all-namespaces
  run_inspect installplans.operators.coreos.com --all-namespaces
  run_inspect operatorgroups.operators.coreos.com --all-namespaces
  run_inspect clusterversions.config.openshift.io --all-namespaces

  run_inspect baremetalhosts.metal3.io --all-namespaces
  run_inspect preprovisioningimages.metal3.io --all-namespaces

  run_inspect placementdecisions.cluster.open-cluster-management.io --all-namespaces
  run_inspect placements.cluster.open-cluster-management.io --all-namespaces
  run_inspect clusterdeployments.hive.openshift.io --all-namespaces
  safe_inspect syncsets hive.openshift.io
  safe_inspect selectorsyncsets hive.openshift.io
  run_inspect clusterimagesets.hive.openshift.io --all-namespaces
  run_inspect machinesets.machine.openshift.io --all-namespaces
  run_inspect clustercurators.cluster.open-cluster-management.io --all-namespaces
  run_inspect clusterpools.hive.openshift.io --all-namespaces
  run_inspect clusterclaims.hive.openshift.io --all-namespaces
  run_inspect machinepools.hive.openshift.io --all-namespaces

  run_inspect managedclusterviews.view.open-cluster-management.io --all-namespaces
  run_inspect managedclusteractions.action.open-cluster-management.io --all-namespaces
  safe_inspect manifestworks work.open-cluster-management.io
  run_inspect managedclusters.cluster.open-cluster-management.io --all-namespaces
  run_inspect managedclusterinfos.internal.open-cluster-management.io --all-namespaces

  run_inspect clustermanagers.operator.open-cluster-management.io --all-namespaces
  run_inspect managedserviceaccounts.authentication.open-cluster-management.io --all-namespaces
  run_inspect managedclustersets.cluster.open-cluster-management.io --all-namespaces
  run_inspect managedclustersetbindings.cluster.open-cluster-management.io --all-namespaces
  run_inspect managedclusterimageregistries.imageregistry.open-cluster-management.io --all-namespaces

  run_inspect validatingwebhookconfigurations.admissionregistration.k8s.io --all-namespaces
  run_inspect mutatingwebhookconfigurations.admissionregistration.k8s.io --all-namespaces

  run_inspect discoveredclusters.discovery.open-cluster-management.io --all-namespaces
  run_inspect discoveryconfigs.discovery.open-cluster-management.io --all-namespaces
  run_inspect discoveredclusterrefreshes.discovery.open-cluster-management.io --all-namespaces

  run_inspect clustermanagementaddons.addon.open-cluster-management.io --all-namespaces
  run_inspect managedclusteraddons.addon.open-cluster-management.io --all-namespaces
  run_inspect addondeploymentconfigs.addon.open-cluster-management.io --all-namespaces
  safe_inspect addontemplates addon.open-cluster-management.io

  run_inspect klusterletconfigs.config.open-cluster-management.io --all-namespaces

  # Collect Lease resources for each managed cluster
  mapfile -t MANAGED_CLUSTER_NAMESPACES < <(oc get managedclusters.cluster.open-cluster-management.io --no-headers=true -o custom-columns="NAME:.metadata.name")
  run_inspect_batched_by_namespace leases.coordination.k8s.io "${MANAGED_CLUSTER_NAMESPACES[@]}"

  run_inspect ns/openshift-monitoring
  run_inspect imagecontentsourcepolicies.operator.openshift.io

  # Topology Aware Lifecycle Manager CRs
  run_inspect ns/openshift-operators
  run_inspect clustergroupupgrades.ran.openshift.io --all-namespaces

  # Inspect Assisted-installer CRs
  run_inspect agent.agent-install.openshift.io --all-namespaces
  run_inspect agentclassification.agent-install.openshift.io --all-namespaces
  run_inspect agentclusterinstall.extensions.hive.openshift.io --all-namespaces
  run_inspect agentserviceconfig.agent-install.openshift.io --all-namespaces
  run_inspect hypershiftagentserviceconfig.agent-install.openshift.io --all-namespaces
  run_inspect infraenv.agent-install.openshift.io --all-namespaces
  run_inspect nmstateconfig.agent-install.openshift.io --all-namespaces

  # Image Based Install Operator CRs
  run_inspect imageclusterinstall.extensions.hive.openshift.io --all-namespaces

  # Cluster API (CAPI) CRs
  run_inspect clusters.cluster.x-k8s.io --all-namespaces
  run_inspect clusterclasses.cluster.x-k8s.io --all-namespaces
  run_inspect machinedeployments.cluster.x-k8s.io --all-namespaces
  run_inspect machines.cluster.x-k8s.io --all-namespaces
  run_inspect machinepools.cluster.x-k8s.io --all-namespaces
  run_inspect rosacontrolplanes.controlplane.cluster.x-k8s.io --all-namespaces
  run_inspect rosamachinepools.infrastructure.cluster.x-k8s.io --all-namespaces

  # CAPM3 CRs
  run_inspect metal3clusters.infrastructure.cluster.x-k8s.io --all-namespaces
  run_inspect metal3clustertemplates.infrastructure.cluster.x-k8s.io --all-namespaces
  run_inspect metal3dataclaims.infrastructure.cluster.x-k8s.io --all-namespaces
  run_inspect metal3datas.infrastructure.cluster.x-k8s.io --all-namespaces
  run_inspect metal3datatemplates.infrastructure.cluster.x-k8s.io --all-namespaces
  run_inspect metal3machines.infrastructure.cluster.x-k8s.io --all-namespaces
  run_inspect metal3machinetemplates.infrastructure.cluster.x-k8s.io --all-namespaces
  run_inspect metal3remediations.infrastructure.cluster.x-k8s.io --all-namespaces
  run_inspect metal3remediationtemplates.infrastructure.cluster.x-k8s.io --all-namespaces

  # CAPOA CRs
  run_inspect openshiftassistedconfigs.bootstrap.cluster.x-k8s.io --all-namespaces
  run_inspect openshiftassistedconfigtemplates.bootstrap.cluster.x-k8s.io --all-namespaces
  run_inspect openshiftassistedcontrolplanes.controlplane.cluster.x-k8s.io --all-namespaces

  # OpenShift console plug-in enablement
  run_inspect consoles.operator.openshift.io
  run_inspect consoleplugins.console.openshift.io

  # Gather any service or event logs for failed agents
  gather_service_and_event_logs_for_failed_agents "${BASE_COLLECTION_PATH}"
}

log "Starting MCE Hub cluster must-gather"
gather_hub
parse_args "$@"
dump_hostedcluster
