#! /bin/bash
# Copyright (c) 2023 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
# shellcheck source=collection-scripts/gather_utils
source "${SCRIPT_DIR}/gather_utils"

export MCE_NAME=""
export OPERATOR_NAMESPACE=""
export DEPLOYMENT_NAMESPACE=""
export HC_NAME=""
export HC_NAMESPACE="clusters" # default hosted cluster namespace

parse_args "$@"

check_if_engine() {
  MCE_NAME=$(oc get multiclusterengines.multicluster.openshift.io --all-namespaces --no-headers=true | awk '{ print $1 }')
  if [[ -n "${MCE_NAME}" ]]; then
    log "Detected MCE resource: \"${MCE_NAME}\" on current cluster. This cluster has been verified as an engine cluster."
    OPERATOR_NAMESPACE=$(oc get pod -l control-plane=backplane-operator --all-namespaces --no-headers=true | head -n 1 | awk '{ print $1 }')
    DEPLOYMENT_NAMESPACE=$(oc get mce "${MCE_NAME}" -o jsonpath='{.spec.targetNamespace}')
    return 0
  fi

  log "No MCE resource detected on the current cluster. This is not an engine cluster (Previous errors can be safely ignored)."
  return 1
}

check_if_hub() {
  log "Detecting Hub cluster by fetching MCH resource..."
  if oc get multiclusterhubs.operator.open-cluster-management.io --all-namespaces; then
    log "Detected MCH resource. This cluster has been verified as a hub cluster."
    return 0
  fi

  log "No MCH resource detected on the current cluster. This is not a hub cluster (Previous errors can be safely ignored)."
  return 1
}

check_if_spoke() {
  log "Detecting Managed cluster by fetching Klusterlet CRD..."
  if oc get crd klusterlets.operator.open-cluster-management.io; then
    log "The current cluster has klusterlets.operator.open-cluster-management.io crd, it is a spoke cluster."
    return 0
  fi

  log "The current cluster does not have klusterlets.operator.open-cluster-management.io crd, it is not a spoke cluster."
  return 1
}

if check_if_engine; then
  if check_if_hub; then
    log "Running ACM MultiClusterHub Must-Gather"
    "${SCRIPT_DIR}/gather_all_logs" &
    pids+=($!)
  fi

  log "Running MulticlusterEngine Must-Gather"
  "${SCRIPT_DIR}/gather_mce_logs" &
  pids+=($!)
fi

if check_if_spoke; then
  log "Running spoke cluster must-gather"
  "${SCRIPT_DIR}/gather_spoke_logs" &
  pids+=($!)
fi

# Check if PID array has any values, if so, wait for them to finish
if [ ${#pids[@]} -ne 0 ]; then
    log "All ACM must-gather scripts have started. Waiting on subprocesses to finish execution."
    wait "${pids[@]}"
    log "All ACM must-gather scripts have completed."
fi

log "ACM must-gather complete."
