#! /bin/bash
# Copyright (c) 2023 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
source ${SCRIPT_DIR}/gather_utils

# Store PIDs of all the subprocesses
pids=()

${SCRIPT_DIR}/gather_mce_logs "$@" &
pids+=($!)

${SCRIPT_DIR}/gather_hub_logs &
pids+=($!)

${SCRIPT_DIR}/gather_observability_logs &
pids+=($!)

${SCRIPT_DIR}/gather_application_lifecycle_logs &
pids+=($!)

${SCRIPT_DIR}/gather_dr_logs &
pids+=($!)

${SCRIPT_DIR}/gather_governance_logs &
pids+=($!)

# Check if PID array has any values, if so, wait for them to finish
if [ ${#pids[@]} -ne 0 ]; then
    log "All ACM must-gather scripts have started. Waiting on subprocesses to finish execution."
    wait "${pids[@]}"
    log "All ACM must-gather scripts have completed."
fi
