#!/bin/bash
#set -x
# Copyright (c) 2023 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

source gather_mce_logs
source gather_hub_logs

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
source ${SCRIPT_DIR}/gather_utils

safe_inspect policies policy.open-cluster-management.io
oc adm inspect policysets.policy.open-cluster-management.io --all-namespaces  --dest-dir=must-gather
oc adm inspect policyautomations.policy.open-cluster-management.io --all-namespaces  --dest-dir=must-gather
oc adm inspect placementbindings.policy.open-cluster-management.io --all-namespaces  --dest-dir=must-gather
oc adm inspect policyreport.wgpolicyk8s.io --all-namespaces  --dest-dir=must-gather
